/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusinessCardRouteImport } from './routes/business-card'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as MapRouteImport } from './routes/map'
import { Route as MinistriesRouteImport } from './routes/ministries'
import { Route as MinistryMindsetRouteImport } from './routes/ministry-mindset'
import { Route as NeedsRouteImport } from './routes/needs'
import { Route as RecommendationsDemoRouteImport } from './routes/recommendations-demo'
import { Route as ReportAbuseRouteImport } from './routes/report-abuse'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ShapeRouteImport } from './routes/shape'
import { Route as StartRouteImport } from './routes/start'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAddChurchRouteImport } from './routes/_authenticated/add-church'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCmsRouteImport } from './routes/_authenticated/cms'
import { Route as AuthenticatedCreateMinistryRouteImport } from './routes/_authenticated/create-ministry'
import { Route as AuthenticatedMeetupsRouteImport } from './routes/_authenticated/meetups'
import { Route as AuthenticatedPostNeedRouteImport } from './routes/_authenticated/post-need'
import { Route as AuthenticatedPostPrayerRouteImport } from './routes/_authenticated/post-prayer'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as ChurchIdRouteImport } from './routes/church.$id'
import { Route as GiftReferenceCodeRouteImport } from './routes/gift-reference.$code'
import { Route as HowItWorksStepRouteImport } from './routes/how-it-works.$step'
import { Route as RoomsSlugRouteImport } from './routes/rooms.$slug'
import { Route as RoomsManageRouteImport } from './routes/rooms.manage'
import { Route as AuthenticatedChurchBoardIdRouteImport } from './routes/_authenticated/church-board.$id'
import { Route as AuthenticatedGiftsIndexRouteImport } from './routes/_authenticated/gifts.index'
import { Route as AuthenticatedGiftsInviteRouteImport } from './routes/_authenticated/gifts.invite'
import { Route as AuthenticatedGiftsListRouteImport } from './routes/_authenticated/gifts.list'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages.$conversationId'
import { Route as AuthenticatedPeopleIdRouteImport } from './routes/_authenticated/people.$id'
import { Route as ApiPublicActivityAlertRouteImport } from './routes/api/public/activity-alert'
import { Route as ApiPublicMeetupRemindersRouteImport } from './routes/api/public/meetup-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCardRoute = BusinessCardRouteImport.update({
  id: '/business-card',
  path: '/business-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesRoute = MinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistryMindsetRoute = MinistryMindsetRouteImport.update({
  id: '/ministry-mindset',
  path: '/ministry-mindset',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsRoute = NeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsDemoRoute = RecommendationsDemoRouteImport.update({
  id: '/recommendations-demo',
  path: '/recommendations-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportAbuseRoute = ReportAbuseRouteImport.update({
  id: '/report-abuse',
  path: '/report-abuse',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShapeRoute = ShapeRouteImport.update({
  id: '/shape',
  path: '/shape',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAddChurchRoute = AuthenticatedAddChurchRouteImport.update({
  id: '/add-church',
  path: '/add-church',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCmsRoute = AuthenticatedCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateMinistryRoute =
  AuthenticatedCreateMinistryRouteImport.update({
    id: '/create-ministry',
    path: '/create-ministry',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeetupsRoute = AuthenticatedMeetupsRouteImport.update({
  id: '/meetups',
  path: '/meetups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostNeedRoute = AuthenticatedPostNeedRouteImport.update({
  id: '/post-need',
  path: '/post-need',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostPrayerRoute = AuthenticatedPostPrayerRouteImport.update({
  id: '/post-prayer',
  path: '/post-prayer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ChurchIdRoute = ChurchIdRouteImport.update({
  id: '/church/$id',
  path: '/church/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftReferenceCodeRoute = GiftReferenceCodeRouteImport.update({
  id: '/gift-reference/$code',
  path: '/gift-reference/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksStepRoute = HowItWorksStepRouteImport.update({
  id: '/how-it-works/$step',
  path: '/how-it-works/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/rooms/$slug',
  path: '/rooms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsManageRoute = RoomsManageRouteImport.update({
  id: '/rooms/manage',
  path: '/rooms/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChurchBoardIdRoute =
  AuthenticatedChurchBoardIdRouteImport.update({
    id: '/church-board/$id',
    path: '/church-board/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGiftsIndexRoute = AuthenticatedGiftsIndexRouteImport.update({
  id: '/gifts/',
  path: '/gifts/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGiftsInviteRoute =
  AuthenticatedGiftsInviteRouteImport.update({
    id: '/gifts/invite',
    path: '/gifts/invite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGiftsListRoute = AuthenticatedGiftsListRouteImport.update({
  id: '/gifts/list',
  path: '/gifts/list',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleIdRoute = AuthenticatedPeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicActivityAlertRoute = ApiPublicActivityAlertRouteImport.update({
  id: '/api/public/activity-alert',
  path: '/api/public/activity-alert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMeetupRemindersRoute =
  ApiPublicMeetupRemindersRouteImport.update({
    id: '/api/public/meetup-reminders',
    path: '/api/public/meetup-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/business-card': typeof BusinessCardRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/explore': typeof ExploreRoute
  '/feedback': typeof FeedbackRoute
  '/map': typeof MapRoute
  '/ministries': typeof MinistriesRoute
  '/ministry-mindset': typeof MinistryMindsetRoute
  '/needs': typeof NeedsRoute
  '/recommendations-demo': typeof RecommendationsDemoRoute
  '/report-abuse': typeof ReportAbuseRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shape': typeof ShapeRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/add-church': typeof AuthenticatedAddChurchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cms': typeof AuthenticatedCmsRoute
  '/create-ministry': typeof AuthenticatedCreateMinistryRoute
  '/meetups': typeof AuthenticatedMeetupsRoute
  '/post-need': typeof AuthenticatedPostNeedRoute
  '/post-prayer': typeof AuthenticatedPostPrayerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/church/$id': typeof ChurchIdRoute
  '/gift-reference/$code': typeof GiftReferenceCodeRoute
  '/how-it-works/$step': typeof HowItWorksStepRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms/manage': typeof RoomsManageRoute
  '/church-board/$id': typeof AuthenticatedChurchBoardIdRoute
  '/gifts/invite': typeof AuthenticatedGiftsInviteRoute
  '/gifts/list': typeof AuthenticatedGiftsListRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/people/$id': typeof AuthenticatedPeopleIdRoute
  '/api/public/activity-alert': typeof ApiPublicActivityAlertRoute
  '/api/public/meetup-reminders': typeof ApiPublicMeetupRemindersRoute
  '/gifts/': typeof AuthenticatedGiftsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/business-card': typeof BusinessCardRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/explore': typeof ExploreRoute
  '/feedback': typeof FeedbackRoute
  '/map': typeof MapRoute
  '/ministries': typeof MinistriesRoute
  '/ministry-mindset': typeof MinistryMindsetRoute
  '/needs': typeof NeedsRoute
  '/recommendations-demo': typeof RecommendationsDemoRoute
  '/report-abuse': typeof ReportAbuseRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shape': typeof ShapeRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/add-church': typeof AuthenticatedAddChurchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cms': typeof AuthenticatedCmsRoute
  '/create-ministry': typeof AuthenticatedCreateMinistryRoute
  '/meetups': typeof AuthenticatedMeetupsRoute
  '/post-need': typeof AuthenticatedPostNeedRoute
  '/post-prayer': typeof AuthenticatedPostPrayerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/church/$id': typeof ChurchIdRoute
  '/gift-reference/$code': typeof GiftReferenceCodeRoute
  '/how-it-works/$step': typeof HowItWorksStepRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms/manage': typeof RoomsManageRoute
  '/church-board/$id': typeof AuthenticatedChurchBoardIdRoute
  '/gifts/invite': typeof AuthenticatedGiftsInviteRoute
  '/gifts/list': typeof AuthenticatedGiftsListRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/people/$id': typeof AuthenticatedPeopleIdRoute
  '/api/public/activity-alert': typeof ApiPublicActivityAlertRoute
  '/api/public/meetup-reminders': typeof ApiPublicMeetupRemindersRoute
  '/gifts': typeof AuthenticatedGiftsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/business-card': typeof BusinessCardRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/explore': typeof ExploreRoute
  '/feedback': typeof FeedbackRoute
  '/map': typeof MapRoute
  '/ministries': typeof MinistriesRoute
  '/ministry-mindset': typeof MinistryMindsetRoute
  '/needs': typeof NeedsRoute
  '/recommendations-demo': typeof RecommendationsDemoRoute
  '/report-abuse': typeof ReportAbuseRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shape': typeof ShapeRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/_authenticated/add-church': typeof AuthenticatedAddChurchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/cms': typeof AuthenticatedCmsRoute
  '/_authenticated/create-ministry': typeof AuthenticatedCreateMinistryRoute
  '/_authenticated/meetups': typeof AuthenticatedMeetupsRoute
  '/_authenticated/post-need': typeof AuthenticatedPostNeedRoute
  '/_authenticated/post-prayer': typeof AuthenticatedPostPrayerRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/church/$id': typeof ChurchIdRoute
  '/gift-reference/$code': typeof GiftReferenceCodeRoute
  '/how-it-works/$step': typeof HowItWorksStepRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms/manage': typeof RoomsManageRoute
  '/_authenticated/church-board/$id': typeof AuthenticatedChurchBoardIdRoute
  '/_authenticated/gifts/invite': typeof AuthenticatedGiftsInviteRoute
  '/_authenticated/gifts/list': typeof AuthenticatedGiftsListRoute
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/people/$id': typeof AuthenticatedPeopleIdRoute
  '/api/public/activity-alert': typeof ApiPublicActivityAlertRoute
  '/api/public/meetup-reminders': typeof ApiPublicMeetupRemindersRoute
  '/_authenticated/gifts/': typeof AuthenticatedGiftsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/business-card'
    | '/contact'
    | '/donate'
    | '/explore'
    | '/feedback'
    | '/map'
    | '/ministries'
    | '/ministry-mindset'
    | '/needs'
    | '/recommendations-demo'
    | '/report-abuse'
    | '/reset-password'
    | '/shape'
    | '/start'
    | '/terms'
    | '/add-church'
    | '/admin'
    | '/cms'
    | '/create-ministry'
    | '/meetups'
    | '/post-need'
    | '/post-prayer'
    | '/profile'
    | '/welcome'
    | '/church/$id'
    | '/gift-reference/$code'
    | '/how-it-works/$step'
    | '/rooms/$slug'
    | '/rooms/manage'
    | '/church-board/$id'
    | '/gifts/invite'
    | '/gifts/list'
    | '/messages/$conversationId'
    | '/people/$id'
    | '/api/public/activity-alert'
    | '/api/public/meetup-reminders'
    | '/gifts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/business-card'
    | '/contact'
    | '/donate'
    | '/explore'
    | '/feedback'
    | '/map'
    | '/ministries'
    | '/ministry-mindset'
    | '/needs'
    | '/recommendations-demo'
    | '/report-abuse'
    | '/reset-password'
    | '/shape'
    | '/start'
    | '/terms'
    | '/add-church'
    | '/admin'
    | '/cms'
    | '/create-ministry'
    | '/meetups'
    | '/post-need'
    | '/post-prayer'
    | '/profile'
    | '/welcome'
    | '/church/$id'
    | '/gift-reference/$code'
    | '/how-it-works/$step'
    | '/rooms/$slug'
    | '/rooms/manage'
    | '/church-board/$id'
    | '/gifts/invite'
    | '/gifts/list'
    | '/messages/$conversationId'
    | '/people/$id'
    | '/api/public/activity-alert'
    | '/api/public/meetup-reminders'
    | '/gifts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/business-card'
    | '/contact'
    | '/donate'
    | '/explore'
    | '/feedback'
    | '/map'
    | '/ministries'
    | '/ministry-mindset'
    | '/needs'
    | '/recommendations-demo'
    | '/report-abuse'
    | '/reset-password'
    | '/shape'
    | '/start'
    | '/terms'
    | '/_authenticated/add-church'
    | '/_authenticated/admin'
    | '/_authenticated/cms'
    | '/_authenticated/create-ministry'
    | '/_authenticated/meetups'
    | '/_authenticated/post-need'
    | '/_authenticated/post-prayer'
    | '/_authenticated/profile'
    | '/_authenticated/welcome'
    | '/church/$id'
    | '/gift-reference/$code'
    | '/how-it-works/$step'
    | '/rooms/$slug'
    | '/rooms/manage'
    | '/_authenticated/church-board/$id'
    | '/_authenticated/gifts/invite'
    | '/_authenticated/gifts/list'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/people/$id'
    | '/api/public/activity-alert'
    | '/api/public/meetup-reminders'
    | '/_authenticated/gifts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  BusinessCardRoute: typeof BusinessCardRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  ExploreRoute: typeof ExploreRoute
  FeedbackRoute: typeof FeedbackRoute
  MapRoute: typeof MapRoute
  MinistriesRoute: typeof MinistriesRoute
  MinistryMindsetRoute: typeof MinistryMindsetRoute
  NeedsRoute: typeof NeedsRoute
  RecommendationsDemoRoute: typeof RecommendationsDemoRoute
  ReportAbuseRoute: typeof ReportAbuseRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShapeRoute: typeof ShapeRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  ChurchIdRoute: typeof ChurchIdRoute
  GiftReferenceCodeRoute: typeof GiftReferenceCodeRoute
  HowItWorksStepRoute: typeof HowItWorksStepRoute
  RoomsSlugRoute: typeof RoomsSlugRoute
  RoomsManageRoute: typeof RoomsManageRoute
  ApiPublicActivityAlertRoute: typeof ApiPublicActivityAlertRoute
  ApiPublicMeetupRemindersRoute: typeof ApiPublicMeetupRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-card': {
      id: '/business-card'
      path: '/business-card'
      fullPath: '/business-card'
      preLoaderRoute: typeof BusinessCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries': {
      id: '/ministries'
      path: '/ministries'
      fullPath: '/ministries'
      preLoaderRoute: typeof MinistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministry-mindset': {
      id: '/ministry-mindset'
      path: '/ministry-mindset'
      fullPath: '/ministry-mindset'
      preLoaderRoute: typeof MinistryMindsetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs': {
      id: '/needs'
      path: '/needs'
      fullPath: '/needs'
      preLoaderRoute: typeof NeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations-demo': {
      id: '/recommendations-demo'
      path: '/recommendations-demo'
      fullPath: '/recommendations-demo'
      preLoaderRoute: typeof RecommendationsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-abuse': {
      id: '/report-abuse'
      path: '/report-abuse'
      fullPath: '/report-abuse'
      preLoaderRoute: typeof ReportAbuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shape': {
      id: '/shape'
      path: '/shape'
      fullPath: '/shape'
      preLoaderRoute: typeof ShapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/add-church': {
      id: '/_authenticated/add-church'
      path: '/add-church'
      fullPath: '/add-church'
      preLoaderRoute: typeof AuthenticatedAddChurchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms': {
      id: '/_authenticated/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof AuthenticatedCmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-ministry': {
      id: '/_authenticated/create-ministry'
      path: '/create-ministry'
      fullPath: '/create-ministry'
      preLoaderRoute: typeof AuthenticatedCreateMinistryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetups': {
      id: '/_authenticated/meetups'
      path: '/meetups'
      fullPath: '/meetups'
      preLoaderRoute: typeof AuthenticatedMeetupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-need': {
      id: '/_authenticated/post-need'
      path: '/post-need'
      fullPath: '/post-need'
      preLoaderRoute: typeof AuthenticatedPostNeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-prayer': {
      id: '/_authenticated/post-prayer'
      path: '/post-prayer'
      fullPath: '/post-prayer'
      preLoaderRoute: typeof AuthenticatedPostPrayerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/church/$id': {
      id: '/church/$id'
      path: '/church/$id'
      fullPath: '/church/$id'
      preLoaderRoute: typeof ChurchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-reference/$code': {
      id: '/gift-reference/$code'
      path: '/gift-reference/$code'
      fullPath: '/gift-reference/$code'
      preLoaderRoute: typeof GiftReferenceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works/$step': {
      id: '/how-it-works/$step'
      path: '/how-it-works/$step'
      fullPath: '/how-it-works/$step'
      preLoaderRoute: typeof HowItWorksStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/rooms/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/manage': {
      id: '/rooms/manage'
      path: '/rooms/manage'
      fullPath: '/rooms/manage'
      preLoaderRoute: typeof RoomsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/church-board/$id': {
      id: '/_authenticated/church-board/$id'
      path: '/church-board/$id'
      fullPath: '/church-board/$id'
      preLoaderRoute: typeof AuthenticatedChurchBoardIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gifts/': {
      id: '/_authenticated/gifts/'
      path: '/gifts'
      fullPath: '/gifts/'
      preLoaderRoute: typeof AuthenticatedGiftsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gifts/invite': {
      id: '/_authenticated/gifts/invite'
      path: '/gifts/invite'
      fullPath: '/gifts/invite'
      preLoaderRoute: typeof AuthenticatedGiftsInviteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gifts/list': {
      id: '/_authenticated/gifts/list'
      path: '/gifts/list'
      fullPath: '/gifts/list'
      preLoaderRoute: typeof AuthenticatedGiftsListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/$id': {
      id: '/_authenticated/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof AuthenticatedPeopleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/activity-alert': {
      id: '/api/public/activity-alert'
      path: '/api/public/activity-alert'
      fullPath: '/api/public/activity-alert'
      preLoaderRoute: typeof ApiPublicActivityAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meetup-reminders': {
      id: '/api/public/meetup-reminders'
      path: '/api/public/meetup-reminders'
      fullPath: '/api/public/meetup-reminders'
      preLoaderRoute: typeof ApiPublicMeetupRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddChurchRoute: typeof AuthenticatedAddChurchRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCmsRoute: typeof AuthenticatedCmsRoute
  AuthenticatedCreateMinistryRoute: typeof AuthenticatedCreateMinistryRoute
  AuthenticatedMeetupsRoute: typeof AuthenticatedMeetupsRoute
  AuthenticatedPostNeedRoute: typeof AuthenticatedPostNeedRoute
  AuthenticatedPostPrayerRoute: typeof AuthenticatedPostPrayerRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedChurchBoardIdRoute: typeof AuthenticatedChurchBoardIdRoute
  AuthenticatedGiftsInviteRoute: typeof AuthenticatedGiftsInviteRoute
  AuthenticatedGiftsListRoute: typeof AuthenticatedGiftsListRoute
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
  AuthenticatedPeopleIdRoute: typeof AuthenticatedPeopleIdRoute
  AuthenticatedGiftsIndexRoute: typeof AuthenticatedGiftsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddChurchRoute: AuthenticatedAddChurchRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCmsRoute: AuthenticatedCmsRoute,
  AuthenticatedCreateMinistryRoute: AuthenticatedCreateMinistryRoute,
  AuthenticatedMeetupsRoute: AuthenticatedMeetupsRoute,
  AuthenticatedPostNeedRoute: AuthenticatedPostNeedRoute,
  AuthenticatedPostPrayerRoute: AuthenticatedPostPrayerRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedChurchBoardIdRoute: AuthenticatedChurchBoardIdRoute,
  AuthenticatedGiftsInviteRoute: AuthenticatedGiftsInviteRoute,
  AuthenticatedGiftsListRoute: AuthenticatedGiftsListRoute,
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
  AuthenticatedPeopleIdRoute: AuthenticatedPeopleIdRoute,
  AuthenticatedGiftsIndexRoute: AuthenticatedGiftsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  BusinessCardRoute: BusinessCardRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  ExploreRoute: ExploreRoute,
  FeedbackRoute: FeedbackRoute,
  MapRoute: MapRoute,
  MinistriesRoute: MinistriesRoute,
  MinistryMindsetRoute: MinistryMindsetRoute,
  NeedsRoute: NeedsRoute,
  RecommendationsDemoRoute: RecommendationsDemoRoute,
  ReportAbuseRoute: ReportAbuseRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShapeRoute: ShapeRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  ChurchIdRoute: ChurchIdRoute,
  GiftReferenceCodeRoute: GiftReferenceCodeRoute,
  HowItWorksStepRoute: HowItWorksStepRoute,
  RoomsSlugRoute: RoomsSlugRoute,
  RoomsManageRoute: RoomsManageRoute,
  ApiPublicActivityAlertRoute: ApiPublicActivityAlertRoute,
  ApiPublicMeetupRemindersRoute: ApiPublicMeetupRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
